// ============> accessChat Constants

export const ACESSCHAT_REQUEST_START = "ACESSCHAT_REQUEST_START"
export const ACESSCHAT_REQUEST_SCCUESS = "ACESSCHAT_REQUEST_SCCUESS"
export const ACESSCHAT_REQUEST_FAILED = "ACESSCHAT_REQUEST_FAILED"

// ============> FetchAllChat Constants

export const FETCHCHAT_REQUEST_START = "FETCHCHAT_REQUEST_START"
export const FETCHCHAT_REQUEST_SCCUESS = "FETCHCHAT_REQUEST_SCCUESS"
export const FETCHCHAT_REQUEST_FAILED = "FETCHCHAT_REQUEST_FAILED"

// ============> CreateGroup Constants

export const  CREATEGROUP_REQUEST_START = "CREATEGROUP_REQUEST_START"
export const CREATEGROUP_REQUEST_SCCUESS = "CREATEGROUP_REQUEST_SCCUESS"
export const CREATEGROUP_REQUEST_FAILED = "CREATEGROUP_REQUEST_FAILED"

// ============> Change Group Name Constants

export const CHANGE_GROUPNAME_START = "CHANGE_GROUPNAME_START"
export const CHANGE_GROUPNAME_SUCCESS = "CHANGE_GROUPNAME_SUCCESS"
export const CHANGE_GROUPNAME_FAILED = "CHANGE_GROUPNAME_FAILED"

// ============> Add User To Group Constants

export const ADD_USER_IN_GROUP_START = "ADD_USER_IN_GROUP_START"
export const ADD_USER_IN_GROUP_SUCCESS = "ADD_USER_IN_GROUP_SUCCESS"
export const ADD_USER_IN_GROUP_FAILED = "ADD_USER_IN_GROUP_FAILED"

// ============> Add User To Group Constants

export const DELETEUSER_GROUP_START = "DELETEUSER_GROUP_START"
export const DELETEUSER_GROUP_SUCCESS = "DELETEUSER_GROUP_SUCCESS"
export const DELETEUSER_GROUP_FAILED = "DELETEUSER_GROUP_FAILED"
